[lint]
select = [
    #"D",     # pydocstyle
    "E4",
    "E7",
    "E9",
    "F",     # pyflakes
    "I",     # isort
    #"N",     # pep8 naming
    "UP",    # pyupgrade
    "B",     # bugbear
    "S",     # security
    "BLE",   # no blind except
    "COM",   # enforce trailing comma
    "C4",    # commas
    "T10",   # catch dgb breakpoints
    "EM",    # exception can't be string literal
    "EXE",   # flake8-executable
    "TRY",   # disallow try/except antipatterns
]
ignore = [
    "S311",  # cryptographic random number
    "S101",  # assert statements
    "S602",  # using shell=True with subprocess
    "COM812",
    "TRY003", # long exception messages
]

[lint.pydocstyle]
# Use Google-style docstrings
convention = "google"
